### ISSUE TITLE
module 'ast' has no attribute 'get_source_segment'

### ISSUE THREAD

**Issue by eafpres** [jungerm2/JupyterLazyLoader#1]
I was trying to test this.
Here is a screenshot of my notebook and what happens.
1st message is 
```
The lazyimport module is not an IPython extension.
```
Then the error trying to use the module.
![image](https://user-images.githubusercontent.com/30508983/107706348-6835cc00-6c7d-11eb-8317-4b299e9a8de6.png)

Any suggestions to overcome this?

**Comment by jungerm2** [comment]
Good catch! I forgot to mention this in the README, but the code as-is, depends on python 3.8+ as it uses this function (see [here](https://docs.python.org/3/library/ast.html#ast.get_source_segment)). There's probably a way to overcome this and make it work for older versions. What version do you have?

**Comment by jungerm2** [comment]
I haven't extensively tested this on different python installs yet as I wasn't sure if it would gain traction. If it does, I'll probably package it properly and add some versioning tests via poetry.

**Comment by eafpres** [comment]
> What version do you have?

I'm running 3.7.4; I'll set up an env w/3.8 and test and report back here.

**Comment by jungerm2** [comment]
Awesome thanks!
I'm going to look into how to add support for earlier versions, but it seems that parsing the AST (which is how we find what gets imported) is much harder in older versions as the API wasn't exposed. I'll post an update here if/when I have one.

**Comment by eafpres** [comment]
> Awesome thanks!

This may take a bit longer; I'm on Windows and I need to figure out how to not change all my envs to 3.8 or 3.9.

**Comment by jungerm2** [comment]
No problem, I appreciate the help so take all the time you need! 

If you use conda you can do so like this:
```
conda create -n myenv python=3.8
```

See step 3 [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands) for more.

**Comment by eafpres** [comment]
> If you use conda

I am migrating away from conda. I’m using venv in Powershell most of the time. Python wants me to use an installer which I am concerned will change my existing envs. I’ll figure it out, or do it on Linux.

**Comment by eafpres** [comment]
I was able to get this to work using a new env with Python 3.8.8.
Thanks
